//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FootballTeamsTable
    {
        public int Id { get; set; }
        public string Team { get; set; }
        public string Record { get; set; }
        public string DateOfGame { get; set; }
    }
}
